import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NextAuthProvider } from "./providers";

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Bici-Vic",
  description: "Generated by create next app",
};
import NavScroll from "./uiComponents/nav";
 
export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthProvider>
          <NavScroll />
          <main>{children}</main>
        </NextAuthProvider>
      </body>
    </html>
  )
}
