export const regimenContratacion = [
  { id: "02", descripcion: "Sueldos y salarios" },
  { id: "03", descripcion: "Jubilados" },
  { id: "04", descripcion: "Pensionados" },
  { id: "05", descripcion: "Asimilados a salarios miembros sociedades cooperativas producción" },
  { id: "06", descripcion: "Asimilados a salarios miembros sociedades personas físicas" },
  { id: "07", descripcion: "Asimilados a salarios rendimientos anticipados" },
  { id: "08", descripcion: "Asimilados a salarios otros" },
  { id: "09", descripcion: "Asimilados a salarios otros ingresos por salarios" },
  { id: "10", descripcion: "Asimilados a salarios pagados por entidades no lucrativas" }
];

export const tipoContrato = [
  { id: "01", descripcion: "Contrato de trabajo por tiempo indeterminado" },
  { id: "02", descripcion: "Contrato de trabajo para obra determinada" },
  { id: "03", descripcion: "Contrato de trabajo por tiempo determinado" },
  { id: "04", descripcion: "Contrato de trabajo por temporada" },
  { id: "05", descripcion: "Contrato de trabajo sujeto a prueba" },
  { id: "06", descripcion: "Contrato de trabajo con capacitación inicial" },
  { id: "07", descripcion: "Modalidad de contratación por pago de hora laborada" },
  { id: "08", descripcion: "Modalidad de trabajo por comisión laboral" },
  { id: "09", descripcion: "Modalidades de contratación donde no existe relación de trabajo" },
  { id: "10", descripcion: "Jubilación, pensión, retiro" },
  { id: "99", descripcion: "Otro contrato" }
];

export const tipoJornada = [
  { id: "01", descripcion: "Diurna" },
  { id: "02", descripcion: "Nocturna" },
  { id: "03", descripcion: "Mixta" },
  { id: "04", descripcion: "Por hora" },
  { id: "05", descripcion: "Reducida" },
  { id: "06", descripcion: "Continuada" },
  { id: "07", descripcion: "Partida" },
  { id: "08", descripcion: "Por turnos" },
  { id: "99", descripcion: "Otra Jornada" }
];

export const periodicidadPago = [
  { id: "01", descripcion: "Diario" },
  { id: "02", descripcion: "Semanal" },
  { id: "03", descripcion: "Catorcenal" },
  { id: "04", descripcion: "Quincenal" },
  { id: "05", descripcion: "Mensual" },
  { id: "06", descripcion: "Bimestral" },
  { id: "07", descripcion: "Unidad obra" },
  { id: "08", descripcion: "Comisión" },
  { id: "09", descripcion: "Precio alzado" },
  { id: "99", descripcion: "Otra Periodicidad" }
];

export const riesgoPuesto = [
  { id: "1", descripcion: "Clase I" },
  { id: "2", descripcion: "Clase II" },
  { id: "3", descripcion: "Clase III" },
  { id: "4", descripcion: "Clase IV" },
  { id: "5", descripcion: "Clase V" }
];

export const bancos = [
  { id: "002", descripcion: "BANAMEX" },
  { id: "012", descripcion: "BBVA BANCOMER" },
  { id: "014", descripcion: "SANTANDER" },
  { id: "021", descripcion: "HSBC" },
  { id: "030", descripcion: "BAJIO" },
  { id: "032", descripcion: "IXE" },
  { id: "036", descripcion: "INBURSA" },
  { id: "042", descripcion: "MIFEL" },
  { id: "044", descripcion: "SCOTIABANK" },
  { id: "072", descripcion: "BANORTE" },
  { id: "106", descripcion: "BANK OF AMERICA" },
  { id: "108", descripcion: "MUFG" },
  { id: "110", descripcion: "JP MORGAN" },
  { id: "112", descripcion: "BMONEX" },
  { id: "113", descripcion: "VE POR MAS" },
  { id: "126", descripcion: "CREDIT SUISSE" },
  { id: "127", descripcion: "AZTECA" },
  { id: "128", descripcion: "AUTOFIN" },
  { id: "129", descripcion: "BARCLAYS" },
  { id: "130", descripcion: "COMPARTAMOS" },
  { id: "132", descripcion: "MULTIVA BANCO" },
  { id: "133", descripcion: "ACTINVER" },
  { id: "134", descripcion: "WAL-MART" },
  { id: "135", descripcion: "NAFIN" },
  { id: "136", descripcion: "INTERBANCO" },
  { id: "137", descripcion: "BANCOPPEL" },
  { id: "138", descripcion: "ABC CAPITAL" },
  { id: "139", descripcion: "UBS BANK" },
  { id: "140", descripcion: "CONSUBANCO" },
  { id: "141", descripcion: "VOLKSWAGEN" },
  { id: "143", descripcion: "CIBANCO" },
  { id: "145", descripcion: "BBASE" },
  { id: "147", descripcion: "BANKAOOL" },
  { id: "148", descripcion: "PAGATODO" },
  { id: "150", descripcion: "MIZUHO BANK" },
  { id: "151", descripcion: "SABADELL" },
  { id: "152", descripcion: "BANCREA" },
  { id: "153", descripcion: "PROGRESO" },
  { id: "154", descripcion: "BANCO SHINHAN" },
  { id: "155", descripcion: "ICBC" },
  { id: "156", descripcion: "BANCO S3" },
  { id: "157", descripcion: "BANCO COVALTO" },
  { id: "158", descripcion: "BANCO BANCREA" },
  { id: "159", descripcion: "BANK OF CHINA" },
  { id: "160", descripcion: "BANCO STARTUP" },
  { id: "166", descripcion: "BANCO DEL BIENESTAR" },
  { id: "168", descripcion: "HIPOTECARIA FEDERAL" },
  { id: "600", descripcion: "MONEXCB" },
  { id: "601", descripcion: "GBM" },
  { id: "602", descripcion: "MASARI" },
  { id: "605", descripcion: "VALUE" },
  { id: "608", descripcion: "VECTOR" },
  { id: "614", descripcion: "ACCIVAL" },
  { id: "615", descripcion: "MERRILL LYNCH" },
  { id: "616", descripcion: "FINAMEX" },
  { id: "617", descripcion: "VALMEX" },
  { id: "618", descripcion: "ÚNICA" },
  { id: "619", descripcion: "MAPFRE" },
  { id: "620", descripcion: "PROFUTURO" },
  { id: "621", descripcion: "CB ACTINVER" },
  { id: "622", descripcion: "OACTIN" },
  { id: "623", descripcion: "SKANDIA" },
  { id: "626", descripcion: "CBDEUTSCHE" },
  { id: "627", descripcion: "ZURICH" },
  { id: "628", descripcion: "ZURICHVI" },
  { id: "629", descripcion: "SU CASITA" },
  { id: "630", descripcion: "CB INTERCAM" },
  { id: "631", descripcion: "CI BOLSA" },
  { id: "632", descripcion: "BULLTICK CB" },
  { id: "633", descripcion: "STERLING" },
  { id: "634", descripcion: "FINCOMUN" },
  { id: "636", descripcion: "HDI SEGUROS" },
  { id: "637", descripcion: "ORDER" },
  { id: "638", descripcion: "AKALA" },
  { id: "640", descripcion: "CB JPMORGAN" },
  { id: "642", descripcion: "REFORMA" },
  { id: "646", descripcion: "STP" },
  { id: "647", descripcion: "TELECOMM" },
  { id: "648", descripcion: "EVERCORE" },
  { id: "649", descripcion: "SKANDIA" },
  { id: "651", descripcion: "SEGMTY" },
  { id: "652", descripcion: "ASEA" },
  { id: "653", descripcion: "KUSPIT" },
  { id: "655", descripcion: "SOFIEXPRESS" },
  { id: "656", descripcion: "UNAGRA" },
  { id: "659", descripcion: "OPCIONES EMPRESARIALES DEL NOROESTE" },
  { id: "670", descripcion: "LIBERTAD" },
  { id: "901", descripcion: "CLS" },
  { id: "902", descripcion: "INDEVAL" },
  { id: "999", descripcion: "N/A" }
];

export const usoCFDI = [
   { id: "99", descripcion: "Por Definir" },
]